export { Entity } from './entity';
export { AggregateRoot } from './aggregate-root';
export { ValueObject } from './value-object';
export { DomainEvent } from './domain-event';
export type { DomainEventProps } from './domain-event';
export type { IRepository, IReadRepository } from './repository';
export { requireAggregate } from './repository';
export { Specification, specification } from './specification';
export { DomainService } from './domain-service';
export type { DomainServiceContext } from './domain-service';
export { SystemClock, systemClock } from './clock';
export type { Clock } from './clock';
export { generateCorrelationId, asCorrelationId } from './correlation-id';
export type { UnitOfWork } from './unit-of-work';
export { toEventEnvelope } from './event-mapper';
export type { ToEventEnvelopeOptions } from './event-mapper';
